name: crates.io

on:
  release:
    types:
      - published

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --token $MODIO_TOKEN --verbose
        env:
          MODIO_TOKEN: ${{ secrets.MODIO_API_TOKEN }}
